### PR TITLE
Upgrade version of pebble

### PR DESCRIPTION
**Pull request by tgalopin**
Required to fix https://github.com/acmephp/acmephp/pull/139.

### CODE REVIEW

**Comment by cpu** [comment]
:wave: @tgalopin,

Does it help you at all to know that [Pebble recently added its own Dockerfile](https://github.com/letsencrypt/pebble#docker-image)? I've also been pushing images to [Docker Hub](https://hub.docker.com/r/letsencrypt/pebble/). From the looks of this project's `Dockerfile` it seems like you can probably get away with just customizing env vars at runtime with the upstream Dockerfile.

Sorry if I'm telling you things you've already considered and discounted :-)

**Comment by tgalopin** [comment]
Wow! Do you have a bot tracking the repositories related to ACME to be so quick?

Thanks for the feedback :) ! You are indeed right, it may be a good time to switch to the official Docker images. What do you think @jderusse ?

**Comment by cpu** [comment]
> Wow! Do you have a bot tracking the repositories related to ACME to be so quick?

:laughing: Just lots of Gmail filters and some Github follows :no_entry_sign: :robot:

**Comment by tgalopin** [comment]
For now, I'll merge this one in order to fix the related PR, but let's consider switching to the official pebble image indeed :) .

One of the biggest reason to use our own image is the control it gives us over versioning. I don't like how many images in the Docker ecosystem use only one or a few tags (only latest and majors), leading to problems appearing without code change on our side.

It doesn't seem to be the case with pebble though, thanks for this :) ! I think it's important you keep creating tags regularly so that people can rely on a specific version and upgrade when they need.

**Comment by cpu** [comment]
> For now, I'll merge this one in order to fix the related PR, but let's consider switching to the official pebble image indeed :) .

Sounds good :+1: My suggestion would probably have been better as a new issue instead of a comment on this PR.

> It doesn't seem to be the case with pebble though, thanks for this :) ! I think it's important you keep creating tags regularly so that people can rely on a specific version and upgrade when they need.

That's good to hear! I wasn't sure what sort of tagging approach would work best. Any other feedback you might have about ways to make Pebble/the dockerfile better for your project's needs would be well received.

Thanks!

**Pull request merged**
